// Char converter
export const CHANGE_SRC_KEY = "CHANGE_SRC_KEY";
export const CHANGE_DESC_KEY = "CHANGE_DESC_KEY";

// Page Format 
export const TOGGLE_AUTO_INIT_PRINT_AREA = "TOGGLE_AUTO_INIT_PRINT_AREA";
export const CHANGE_PAGE_SIZE = "CHANGE_PAGE_SIZE";
export const CHANGE_ORIENTATION = "CHANGE_ORIENTATION";  
export const CHANGE_BLACK_ANĐ_WHITE = "CHANGE_BLACK_ANĐ_WHITE";  